version: "3.8"
services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8383:80"
    depends_on: 
      - app
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
